const mongoose = require("mongoose");
const courseSchema = new mongoose.Schema({
    courseName:{
        type:String,
        required:true,
        trim:true,
    },
    instructor:{
        type:mongoose.Schema.Types.ObjectId,
        res:"instructor",
        required:true,
    },
    courseDetails:{
        price:{
            type:Number,
            required:true,
        },
        courseDescription:{
            type:String,
            required:true,
        },
        courseCatagory:{
            type:String,
            required:true,
        },
        thumbnail:{
            type:String,
            required:true,
        },
        tags:[{
            type:String,
            required:true,
        }],
        benifits:{
            type:String,
            required:true
        },
        requirements:{
            type:String,
            required:true
        }
    },
    isPublic:{
        type:Boolean,
        required:true,
    },
    dateCreated:{
        type:Date,
        required:true,
    },
    ratingCount:{
        type:Number,
        required:true,
    },
    ratingSum:{
        type:Number,
        required:true,
    },
    reviews:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"review",
    }],
    enrolledStudents:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"user"
    }],
    
    //sections schema is wrong there needs to be only 2 levels 1 is section and 2 is subsectin which will have only 1 task in it
    sections:[{
        sectionName:String,
        subSection:[{
            subSectionName:String,
                taskType:{
                    type:String,
                    required:true,
                },
                taskURL:{
                    type:String,
                    required:true,
                },
                taskTitle:{
                    type:String,
                    required:true,
                },
                taskDescription:{
                    type:String,
                    required:true,
                },
                playbackTime:{
                    type:Number,
                    required:true,
                },
            }]
        }]
    })

module.exports = mongoose.model("course",courseSchema);