const mongoose = require("mongoose");
const courseSchema = new mongoose.Schema({
    courseName:{
        type:String,
        required:true,
        trim:true,
    },
    instructor:{
        type:mongoose.Schema.Types.ObjectId,
        res:"instructor",
        required:true,
    },
    courseDetails:{
        price:{
            type:Number,
            required:true,
        },
        courseDescription:{
            type:String,
            required:true,
        },
        courseCatagory:{
            type:String,
            required:true,
        },
        thumbnail:{
            type:String,
            required:true,
        },
        tags:[{
            type:String,
            required:true,
        }],
        benifits:{
            type:String,
            required:true
        },
        requirements:{
            type:String,
            required:true
        }
    },
    isPublic:{
        type:Boolean,
        required:true,
    },
    dateCreated:{
        type:Date,
        required:true,
    },
    ratingCount:{
        type:Number,
        required:true,
    },
    ratingSum:{
        type:Number,
        required:true,
    },
    reviews:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"review",
    }],
    enrolledStudents:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"user"
    }],
    sections:[{
        sectionName:String,
        lessons:[{
            lessonName:String,
            lectures:[{
                lesctureName:String,
                tasks:[{
                    taskType:{
                        type:String,
                        required:true,
                    },
                    taskTitle:String,
                    taskDescription:String,
                    playbackTime:Number,
                }]
            }]
        }]
    }]
    
})

module.exports = mongoose.model("course",courseSchema);